version: '3'
services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888;2181
    volumes:
      - ./store/zookeeper/data:/data
      - ./store/zookeeper/zookeeper-datalog:/datalog
    networks:
      - local_net
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181" ]
      interval: 30s
      timeout: 10s
      retries: 3

  etcd:
    container_name: etcd
    image: bitnami/etcd:3.5.7
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
       - ALLOW_NONE_AUTHENTICATION=yes
    privileged: true
    volumes:
      - ./store/etcd/data:/bitnami/etcd/data
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - local_net

  redis:
    container_name: redis
    image: redis:7.2.3
    restart: always
    volumes:
      - ./store/redis/data:/data
      - ./config/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    command: redis-server /etc/redis/redis.conf
    networks:
      - local_net

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - MODE=standalone
      - JVM_XMS=512m
      - JVM_XMX=512m
      - NACOS_AUTH_ENABLE=true
      - NACOS_SERVER_PORT=8848
      - NACOS_AUTH_IDENTITY_KEY=d72768e49f60cf39c86aefcd63106262
      - NACOS_AUTH_IDENTITY_VALUE=7e671101b7b872350e5829ba7a3c2c3a
      - NACOS_AUTH_TOKEN=MT1TjuOgGRUFIM7rpsGXaux+bjM4WDNXohKr1UJKDxk=
#      - NACOS_AUTH_ENABLE_USERAGENT_AUTH_WHITE=true # dev env
    volumes:
      - ./store/nacos-logs:/home/nacos/logs
      - ./store/nacos-data:/home/nacos/data
    networks:
      - local_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    platform: linux/amd64
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: ["consul", "agent", "-server", "-bootstrap-expect=1", "-ui", "-client=0.0.0.0", "-data-dir=/consul/data"]
    volumes:
      - ./store/consul-data:/consul/data
    networks:
      - local_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  local_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16